# Generated by Django 5.0.4 on 2024-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desagregacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=200)),
                ('wats', models.CharField(max_length=200)),
                ('sound_system', models.CharField(max_length=200)),
                ('tv', models.CharField(max_length=200)),
                ('play', models.CharField(max_length=200)),
                ('computer', models.CharField(max_length=200)),
                ('clothes_iron', models.CharField(max_length=200)),
                ('clothes_wash', models.CharField(max_length=200)),
                ('refrigerator', models.CharField(max_length=200)),
                ('oven', models.CharField(max_length=200)),
                ('estado', models.IntegerField(max_length=200)),
            ],
            options={
                'db_table': 'Desagregacion',
            },
        ),
    ]
